### ISSUE TITLE
TIF compared to original ERT indexed shape

### ISSUE THREAD

**Issue by inspirit** [ChrisYang/TIFfacealignment#1]
Hi, i was wondering if you compared TIF implementation results on 68pt face shape?
i did some tests and TIF performs worse compared to original indexed shape implementation
0.049 vs 0.046 (normalized mean error)

**Comment by ChrisYang** [comment]
For dense landmarks and frontal faces, we expect TIF performs similarly to ERT (0.049 vs 0.046 are similar to me). The benefits of TIF are for samples with sparse landmarks and large head pose variation.
